### PR TITLE
Placement policy validation against LiveMigration KubeVirt feature gate

### LINKED ISSUE #120: LiveMigration feature gate is not enabled
is this feature gate required for VM imports to work? Btw some imports work fine without it

Error
```
Error while creating virtual machine: admission webhook "virtualmachine-validator.kubevirt.io" denied the request: LiveMigration feature gate is not enabled
```

VirtualMachineImport

```yaml
apiVersion: v2v.kubevirt.io/v1alpha1
kind: VirtualMachineImport
metadata:
  generateName: vm-import-win2012-
  annotations:
    vmimport.v2v.kubevirt.io/progress: '40'
    vmimport.v2v.kubevirt.io/source-vm-initial-state: down
  selfLink: >-
    /apis/v2v.kubevirt.io/v1alpha1/namespaces/default/virtualmachineimports/vm-import-win2012-9v8hd
  resourceVersion: '530480'
  name: vm-import-win2012-9v8hd
  uid: cf296899-f976-494e-8630-cfeed911a54e
  creationTimestamp: '2020-04-21T09:39:11Z'
  generation: 1
  namespace: default
spec:
  providerCredentialsSecret:
    name: admin-mburman-4-upgrade-env-sc-xds8w
    namespace: default
  source:
    ovirt:
      mappings:
        diskMappings:
          - source:
              id: 5648013d-ece9-4ddc-8f00-3709c5c8831f
            target:
              name: null
        networkMappings:
          - source:
              id: 762b1e45-bf13-4c09-815e-34a8016b0a6c
            type: pod
      vm:
        id: 367e1089-a4e7-4a66-8dc5-e22605f06d11
  startVm: false
  targetVmName: win2012
status:
  conditions:
    - lastHeartbeatTime: '2020-04-21T09:39:19Z'
      lastTransitionTime: '2020-04-21T09:39:19Z'
      message: Validation completed successfully
      reason: ValidationCompleted
      status: 'True'
      type: Valid
    - lastHeartbeatTime: '2020-04-21T09:39:19Z'
      lastTransitionTime: '2020-04-21T09:39:19Z'
      message: >-
        VM specifies IO Threads: 1, VM has NUMA tune mode secified: interleave,
        Interface 1d6564e3-1256-48be-9cce-2ff523559b97 uses profile with a
        network filter with ID: d2370ab4-fee3-11e9-a310-8c1645ce738e.
      reason: MappingRulesVerificationReportedWarnings
      status: 'True'
      type: MappingRulesVerified
    - lastHeartbeatTime: '2020-04-21T09:41:46Z'
      lastTransitionTime: '2020-04-21T09:41:46Z'
      message: Copying virtual machine disks
      reason: CopyingDisks
      status: 'True'
      type: Processing
    - lastHeartbeatTime: '2020-04-21T09:41:46Z'
      lastTransitionTime: '2020-04-21T09:39:19Z'
      message: >-
        Error while creating virtual machine: admission webhook
        "virtualmachine-validator.kubevirt.io" denied the request: LiveMigration
        feature gate is not enabled
      reason: VMCreationFailed
      status: 'False'
      type: Succeeded

```

#### log:

```js
{"level":"info","ts":1587462106.5013237,"logger":"controller_virtualmachineimport","msg":"VirtualMachineImport has already been validated positively. Skipping re-validation","Request.Namespace":"default","Request.Name":"vm-import-win2012-9v8hd"}
{"level":"info","ts":1587462106.5118895,"logger":"controller_virtualmachineimport","msg":"No matching template was found for the virtual machine using empty vm definition","Request.Namespace":"default","Request.Name":"vm-import-win2012-9v8hd"}
{"level":"info","ts":1587462106.520361,"logger":"controller_virtualmachineimport","msg":"Creating a new VM","Request.Namespace":"default","Request.Name":"vm-import-win2012-9v8hd","VM.Namespace":"default","VM.Name":"win2012"}
{"level":"error","ts":1587462107.0082643,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"virtualmachineimport-controller","request":"default/vm-import-win2012-9v8hd","error":"VirtualMachine.kubevirt.io \"\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tvm-import-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tvm-import-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tvm-import-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tvm-import-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tvm-import-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tvm-import-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tvm-import-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1587462108.009449,"logger":"controller_virtualmachineimport","msg":"Reconciling VirtualMachineImport","Request.Namespace":"default","Request.Name":"vm-import-vm1-rrbhp"}
```

### PR DESCRIPTION
**Pull request by jakub-dzon**
Fixes #120
```release-note
NONE
```

Signed-off-by: Jakub Dzon <jdzon@redhat.com>

### CODE REVIEW

File: pkg/providers/ovirt/validation/validators/validator-wrapper.go [hunk 1]
```diff
@@ -23,12 +28,17 @@ func NewValidatorWrapper(client client.Client) *ValidatorWrapper {
...
 }
 
 // ValidateVM wraps validators package implementation of ValidateVM function
 func (v *ValidatorWrapper) ValidateVM(vm *ovirtsdk.Vm) []ValidationFailure {
-	return ValidateVM(vm)
+	kvConfig, err := v.kvConfigProvider.GetConfig()
+	if err != nil {
+		logger.Error(err, "Cannot get KubeVirt cluster config.")
+	}
+	return ValidateVM(vm, kvConfig)
```
Comment (pkliczewski) [inline pkg/providers/ovirt/validation/validators/validator-wrapper.go:41]: What would be `kvConfig` value when we get an `err` while getting it? I am especially interested in `LiveMigrationEnabled` because we use it even we have an issue to get it.

Comment (jakub-dzon) [reply pkg/providers/ovirt/validation/validators/validator-wrapper.go:41]: It will be initialized with zero values and will claim there is no support for live migration. 
IMO that's optimal approach to handling that error here; if we propagated the error up the call stack, we would always re-queue the request and in current implementation we will re-queue it only if live migration feature gate state was important (source vm has configuration requiring it and we fail validation due to assumed lack of support for it).
What's your opinion?

Comment (pkliczewski) [reply pkg/providers/ovirt/validation/validators/validator-wrapper.go:41]: I am not sure. Having no kubevirt config seems critical and means that something is not right.

Comment (jakub-dzon) [reply pkg/providers/ovirt/validation/validators/validator-wrapper.go:41]: The KubeVirt configmap is optional and in some regular cases we might not have it; the behaviour of the config provider will be different - it won't return error but the returned config will be the same.

**Review by pkliczewski — APPROVED** [review]

**Review by machacekondra — APPROVED** [review]

**Review by masayag — APPROVED** [review]
